# escape=`
FROM mcr.microsoft.com/windows/servercore:ltsc2019 as core

# Keep the PowerShell commands minimal, just like in drone-s3
SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]

ENV DOCKER_VERSION 19.03.1

# Combine all download and extract operations into a single RUN to minimize layers
RUN Invoke-WebRequest 'http://constexpr.org/innoextract/files/innoextract-1.6-windows.zip' -OutFile 'innoextract.zip' -UseBasicParsing ; `
    Expand-Archive innoextract.zip -DestinationPath C:\ ; `
    Remove-Item -Path innoextract.zip ; `
    [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12 ; `
    Invoke-WebRequest $('https://github.com/docker/toolbox/releases/download/v{0}/DockerToolbox-{0}.exe' -f $env:DOCKER_VERSION) -OutFile 'dockertoolbox.exe' -UseBasicParsing ; `
    C:\innoextract.exe dockertoolbox.exe

FROM mcr.microsoft.com/windows/nanoserver:1809

USER ContainerAdministrator

ENV GODEBUG=netdns=go

COPY --from=core /windows/system32/netapi32.dll /windows/system32/netapi32.dll
COPY --from=core /app/docker.exe C:/bin/docker.exe

LABEL maintainer="Drone.IO Community <drone-dev@googlegroups.com>" `
  org.label-schema.name="Drone Docker" `
  org.label-schema.vendor="Drone.IO Community" `
  org.label-schema.schema-version="1.0"

RUN mkdir C:\bin
ADD release/windows/amd64/drone-docker.exe C:/bin/drone-docker.exe

ENTRYPOINT [ "C:\\bin\\drone-docker.exe" ]